version: '3'
services:
#  nginx:
#    image: nginx:latest
#    container_name: focus_nginx
#    links:
#      - app_backend:app_backend
#      - app_frontend:app_frontend
#    volumes:
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 80:80
  drill:
    image: drill/apache-drill:1.16.0
    stdin_open: true
    tty: true
    ports:
      - 8047:8047
    volumes:
      - ./docker/data:/data/focus
#  app_frontend:
#    links:
#      - app_backend:app_backend
#    build:
#      context: ./frontend
#    volumes:
#      - ./frontend/node_modules:/usr/src/app/node_modules
#      - ./frontend/.nuxt:/usr/src/app/.nuxt
#    environment:
#      BACKEND_HOST: app_backend
#      _AXIOS_BASE_URL_: /
#      API_URL: /
#  app_backend:
#    links:
#      - drill:drill
#    volumes:
#      - ./backend/node_modules:/usr/src/app/node_modules
#    build:
#      context: ./backend
#    environment:
#      DRILL_HOST: drill
